### PR TITLE
fix(ios-sdk): redact filesystem paths in log output

### LINKED ISSUE #81: Remove any PII logging
_🛠️ Refactor suggestion_

**Redact file paths and internals in logs.**

Avoid leaking local paths/objects in info logs. 

```diff
-            logger.info("📂 Using model from SDK: \(currentModel.name) at path: \(actualModelPath)")
+            logger.info("📂 Using model from SDK: \(currentModel.name, privacy: .private(mask: .hash)) at path: \(actualModelPath, privacy: .private)")
```

```diff
-        logger.info("🚀 Initializing with model path: \(modelPath)")
+        logger.info("🚀 Initializing with model path: \(modelPath, privacy: .private)")
```

```diff
-        logger.info("🔍 LLM instance: \(String(describing: llm))")
-        logger.info("🔍 Model path: \(self.modelPath ?? "nil")")
+        logger.info("🔍 LLM instance set")
+        logger.info("🔍 Model path set")
```

Also applies to: 86-86, 149-150

<details>
<summary>🤖 Prompt for AI Agents</summary>

```
In sdk/runanywhere-swift/Modules/LLMSwift/Sources/LLMSwift/LLMSwiftService.swift
around lines 36 (and also at 86 and 149-150), the info logs include full local
file paths and internals; change them to avoid leaking filesystem or object
internals by removing or redacting the full path and any sensitive object
details — log only non-sensitive fields such as the model name or its ID (or the
path's basename), or replace the path with a fixed placeholder like
"<redacted_path>", and ensure any other occurrences at the referenced lines
follow the same rule.
```

</details>

_Originally posted by @coderabbitai[bot] in https://github.com/RunanywhereAI/runanywhere-sdks/pull/45#discussion_r2328395958_

### PR DESCRIPTION
**Pull request by ManthanNimodiya**
## Description

Replace full filesystem paths with `lastPathComponent` in all iOS SDK log
statements to prevent PII leakage. Full paths like
`/Users/alice/Library/Containers/.../Models/llamacpp/smollm2/smollm2.gguf`
were being logged at `info` level, exposing the user's home directory structure
in development and staging environments.

Fixes #81

## Type of Change
- [x] Bug fix

## Testing
- [x] Lint passes locally
- [ ] Added/updated tests for changes

### Platform-Specific Testing (check all that apply)
**Swift SDK / iOS Sample:**
- [ ] Tested on iPhone (Simulator or Device)
- [ ] Tested on iPad / Tablet
- [ ] Tested on Mac (macOS target)

**Kotlin SDK / Android Sample:**
- [ ] Tested on Android Phone (Emulator or Device)
- [ ] Tested on Android Tablet

**Flutter SDK / Flutter Sample:**
- [ ] Tested on iOS
- [ ] Tested on Android

**React Native SDK / React Native Sample:**
- [ ] Tested on iOS
- [ ] Tested on Android

**Playground:**
- [ ] Tested on target platform
- [ ] Verified no regressions in existing Playground projects

**Web SDK / Web Sample:**
- [ ] Tested in Chrome (Desktop)
- [ ] Tested in Firefox
- [ ] Tested in Safari
- [ ] WASM backends load (LlamaCpp + ONNX)
- [ ] OPFS storage persistence verified (survives page refresh)
- [ ] Settings persistence verified (localStorage)

## Labels
- [x] `Swift SDK` - Changes to Swift SDK (`sdk/runanywhere-swift`)

## Checklist
- [x] Code follows project style guidelines
- [x] Self-review completed
- [ ] Documentation updated (if needed)

## Screenshots
N/A — logging-only change, no UI impact.

----

> [!IMPORTANT]
> Redacts full filesystem paths in iOS SDK logs to prevent PII leakage by using `lastPathComponent`.
> 
>   - **Behavior**:
>     - Redacts full filesystem paths in log statements by using `lastPathComponent` instead of full paths.
>     - Affects logging in `DiffusionPlatformService.swift`, `CppBridge+ModelPaths.swift`, and `ArchiveUtility.swift`.
>   - **Logging**:
>     - Updates log statements in `RunAnywhere+Diffusion.swift` and `RunAnywhere+ModelManagement.swift` to use `lastPathComponent`.
>   - **Testing**:
>     - Lint passes locally, but no new tests added.
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=RunanywhereAI%2Frunanywhere-sdks&utm_source=github&utm_medium=referral)<sup> for 8a554039f43f29202f06b1472dc32bed20e65d89. You can [customize](https://app.ellipsis.dev/RunanywhereAI/settings/summaries) this summary. It will automatically update as commits are pushed.</sup>

<h3>Greptile Summary</h3>

Redacts full filesystem paths in iOS SDK log statements by replacing `.path` with `.lastPathComponent` to prevent PII leakage. This prevents usernames and directory structures from being exposed in development and staging logs.

- Successfully redacts paths in 5 files across info, debug, and warning level logs
- However, error message at `DiffusionPlatformService.swift:62` still exposes full `modelPath` when model directory is not found - this should also use `lastPathComponent` for consistency

<h3>Confidence Score: 4/5</h3>

- Safe to merge with one minor fix to error message
- The PR successfully addresses PII leakage in log statements across all changed files, but misses one error message that still exposes the full path. The fix is straightforward and follows the same pattern used elsewhere in the PR.
- DiffusionPlatformService.swift:62 needs the error message updated to redact the path

<h3>Important Files Changed</h3>

| Filename | Overview |
|----------|----------|
| sdk/runanywhere-swift/Sources/RunAnywhere/Features/Diffusion/DiffusionPlatformService.swift | Redacts paths in info/debug logs but error message at line 62 still exposes full `modelPath` when directory not found |
| sdk/runanywhere-swift/Sources/RunAnywhere/Infrastructure/Download/Utilities/ArchiveUtility.swift | Successfully redacts extraction destination paths in info logs |
| sdk/runanywhere-swift/Sources/RunAnywhere/Public/Extensions/Models/RunAnywhere+ModelManagement.swift | Successfully redacts paths in all info/debug/warning logs throughout model loading and path resolution |

</details>

<sub>Last reviewed commit: 8a55403</sub>

## Summary by CodeRabbit

* **Chores**
  * Simplified logging across the SDK to emit only file or directory names (last path components) instead of full filesystem paths during model initialization, resource discovery, path handling, model loading, and archive operations.
  * Reduced log verbosity and sensitive path exposure; no functional behavior, error handling, or public APIs were changed.

### CODE REVIEW

**Comment by shubhammalhotra28** [comment]
Hey @ManthanNimodiya Thanks for the fix. Did you test this though ?

**Comment by ManthanNimodiya** [comment]
@shubhammalhotra28 since the changes only affect the log string (not the actual path passed to the C++ bridge), there's no behavioral difference to test — but your comment was helpful as it prompted me to catch and fix the leaked path in the error message on line 62 which I had missed initially!
Thanks

File: sdk/runanywhere-swift/Sources/RunAnywhere/Features/Diffusion/DiffusionPlatformService.swift [hunk 1]
```diff
@@ -54,17 +54,17 @@ public actor DiffusionPlatformService {
...
         tokenizerSource: DiffusionTokenizerSource = .sd15
     ) async throws {
-        logger.info("Initializing diffusion pipeline from: \(modelPath)")
+        logger.info("Initializing diffusion pipeline from: \(URL(filePath: modelPath).lastPathComponent)")
         logger.info("Tokenizer source: \(tokenizerSource.description)")
 
         // Verify the directory exists
         guard FileManager.default.fileExists(atPath: modelPath) else {
-            throw SDKError.diffusion(.modelNotFound, "Model directory not found: \(modelPath)")
+            throw SDKError.diffusion(.modelNotFound, "Model directory not found: \(URL(filePath: modelPath).lastPathComponent)")
```
Comment (Siddhesh2377) [inline sdk/runanywhere-swift/Sources/RunAnywhere/Features/Diffusion/DiffusionPlatformService.swift]: @ManthanNimodiya Have a look into it

Comment (ManthanNimodiya) [reply sdk/runanywhere-swift/Sources/RunAnywhere/Features/Diffusion/DiffusionPlatformService.swift]: Missed URL(fileURLWithPath:) on line 66 while fixing 57 and 62 — fixed now by extracting a single let modelURL = URL(filePath: modelPath) constant reused across all three call sites.
